$(document).ready(function(){
	$('.collapse').hide();
	$('.expander').next().hide();
	$('.expander').click(function(){
		$(this).next().slideDown(500);
		$(this).slideUp(300);
		$(this).next().next().slideDown(500);
		$('.collapse').click(function(){
			$(this).prev().slideUp(500);
			$(this).slideUp(500);
			$('.expander').slideDown(300);
		})
	})	
})
